require("blackmatov.plugins-setup")

require("blackmatov.core.colors")
require("blackmatov.core.keymaps")
require("blackmatov.core.options")

require("blackmatov.plugins.bufferline")
require("blackmatov.plugins.comment")
require("blackmatov.plugins.gitsigns")
require("blackmatov.plugins.lualine")
require("blackmatov.plugins.mason")
require("blackmatov.plugins.nvim-cmp")
require("blackmatov.plugins.nvim-lspconfig")
require("blackmatov.plugins.nvim-surround")
require("blackmatov.plugins.nvim-tree")
require("blackmatov.plugins.nvim-treesitter")
require("blackmatov.plugins.telescope")
require("blackmatov.plugins.vim-visual-multi")
